import { defineConfig } from 'tsup';

export default defineConfig((options) => ({
	entry: [
		'src/components/core/accordion.tsx',
		'src/components/core/alert-dialog.tsx',
		'src/components/core/alert.tsx',
		'src/components/core/avatar.tsx',
		'src/components/core/badge.tsx',
		'src/components/core/breadcrumb.tsx',
		'src/components/core/button-group.tsx',
		'src/components/core/button.tsx',
		'src/components/core/calendar.tsx',
		'src/components/core/card.tsx',
		'src/components/core/chart.tsx',
		'src/components/core/checkbox.tsx',
		'src/components/core/collapsible.tsx',
		'src/components/core/combobox.tsx',
		'src/components/core/command.tsx',
		'src/components/core/context-menu.tsx',
		'src/components/core/dialog.tsx',
		'src/components/core/drawer.tsx',
		'src/components/core/dropdown-menu.tsx',
		'src/components/core/empty.tsx',
		'src/components/core/field.tsx',
		'src/components/core/hover-card.tsx',
		'src/components/core/input-group.tsx',
		'src/components/core/input-otp.tsx',
		'src/components/core/input.tsx',
		'src/components/core/item.tsx',
		'src/components/core/kbd.tsx',
		'src/components/core/label.tsx',
		'src/components/core/menubar.tsx',
		'src/components/core/navigation-menu.tsx',
		'src/components/core/pagination.tsx',
		'src/components/core/popover.tsx',
		'src/components/core/progress.tsx',
		'src/components/core/radio-group.tsx',
		'src/components/core/resizable.tsx',
		'src/components/core/scroll-area.tsx',
		'src/components/core/select.tsx',
		'src/components/core/separator.tsx',
		'src/components/core/sheet.tsx',
		'src/components/core/sidebar.tsx',
		'src/components/core/skeleton.tsx',
		'src/components/core/slider.tsx',
		'src/components/core/sonner.tsx',
		'src/components/core/switch.tsx',
		'src/components/core/table.tsx',
		'src/components/core/textarea.tsx',
		'src/components/core/tooltip.tsx',
		'src/styles/globals.css',
	],
	format: ['cjs', 'esm'],
	dts: true,
	treeshake: true,
	splitting: true,
	external: ['react'],
	clean: true,
	...options,
}));
